<?php
$_API_URL_USAPPY = 'http://usappy.com/api/';
$_API_URL_UPS = 'http://verify-ups.com/api/';
$_API_SECRET = 'sec';

if (YII_ENV == 'prod') {
    $_API_URL_USAPPY = 'https://usappy.jp/api/';
    $_API_URL_UPS = 'https://usami-p.com/api/';
    $_API_SECRET = 'CJCHG2SEFN';
}

return [
    'api' => [
        'ss' => [
            'url_ss' => $_API_URL_USAPPY . 'ss',
        ],
        'car' => [
            'url_car' => $_API_URL_USAPPY . 'car',
            'url_card_info' => $_API_URL_UPS . 'getmembercard',
            'url_car_info' => $_API_URL_UPS . 'getmembercar',
            'url_update_member_car' => $_API_URL_UPS . 'updmembercar',
            'url_update_member_card' => $_API_URL_UPS . 'updmembercard',
        ],
        'member' => [
            'url_card' => $_API_URL_UPS . 'getcardno',
            'url_member' => $_API_URL_UPS . 'getmemberbasic',
            'url_member_list' => $_API_URL_UPS . 'getmembers',
            'url_update_member' => $_API_URL_UPS . 'updmemberbasic',
        ],
        'zipcode' => [
            'url_addr' => $_API_URL_USAPPY . 'zipcode'
        ],
        'secret' => $_API_SECRET,
    ],
    'd02SyakenCycle' => [
        '' => '',
        '1' => '1',
        '2' => '2',
    ],
    'd03YoyakuSagyoNo' => [
        '0' => '',
        '1' => 'タイヤ',
        '2' => 'オイル',
        '3' => 'バッテリー',
        '4' => 'コーティング',
        '5' => 'リペア',
        '6' => '車検',
        '7' => 'その他',
    ],
    'D03_TANTO_SEIｏD03_TANTO_MEI' => [

    ],
    'M05_COM_CD_TAISA' => range(42000, 42999),
    'adminEmail' => 'admin@example.com',
    'defaultPageSize' => '20',
    'message_save_error' => '保存が失敗しました。',
    'status' => [
        '' => '指定なし',
        '0' => '受付データ',
        '1' => '予約データ',
        '2' => '作業確定',
    ],
    'timeOutLogin' => 1800,
    'zippdf' => [
        'year' => [
            '2016' => '2016',
            '2017' => '2017',
            '2018' => '2018',
            '2019' => '2019',
            '2020' => '2020',
            '2021' => '2021',
            '2022' => '2022',
            '2023' => '2023',
            '2024' => '2024',
        ],
        'month' => [
            '01' => '01',
            '02' => '02',
            '03' => '03',
            '04' => '04',
            '05' => '05',
            '06' => '06',
            '07' => '07',
            '08' => '08',
            '09' => '09',
            '10' => '10',
            '11' => '11',
            '12' => '12'
        ],
        'day' => [
            '01' => '01',
            '02' => '02',
            '03' => '03',
            '04' => '04',
            '05' => '05',
            '06' => '06',
            '07' => '07',
            '08' => '08',
            '09' => '09',
            '10' => '10',
            '11' => '11',
            '12' => '12',
            '13' => '13',
            '14' => '14',
            '15' => '15',
            '16' => '16',
            '17' => '17',
            '18' => '18',
            '19' => '19',
            '20' => '20',
            '21' => '21',
            '22' => '22',
            '23' => '23',
            '24' => '24',
            '25' => '25',
            '26' => '26',
            '27' => '27',
            '28' => '28',
            '29' => '29',
            '30' => '30',
            '31' => '31',
        ]
    ],
    'vat' => 0,
    'route_keep_cookie' => [
        'usappynumberchange/default/index',
        'usappynumberchange/default/confirm',
        'usappynumberchange/default/complete',
        'registworkslip/default/index',
        'inspection/denpyo/create',
        'inspection/denpyo-preview/index',
        'inspection/denpyo-detail/detail',
    ],
    'admin_user' => [
        '0' => [
            'ssid' => 'fcc',
            'password' => 'npaZd3Ec'
        ],
        '1' => [
            'ssid' => 'dom',
            'password' => 'x3Y4x55p89kz'
        ]
    ],
    'admin_login' => [
        '0' => [
            'ssid' => 'system',
            'password' => 'manager'
        ],
    ],
    'branch' => [
        '202480' => '東日本宇佐美　北海道支店',
        '283963' => '東日本宇佐美　東北支店',
        '326855' => '東日本宇佐美　上信越支店',
        '458926' => '東日本宇佐美　東京販売支店',
        '458935' => '東日本宇佐美　神奈川販売支店',
        '458944' => '東日本宇佐美　埼玉栃木販売支店',
        '458953' => '東日本宇佐美　千葉茨城販売支店',
        '451987' => '西日本宇佐美　東海支店',
        '457142' => '西日本宇佐美　中部支店',
        '513545' => '西日本宇佐美　北陸支店',
        '575167' => '西日本宇佐美　関西支店',
        '603074' => '西日本宇佐美　山陽支店',
        '784351' => '西日本宇佐美　九州支店',
        '458720' => 'ダイツー',
    ],
    'sateiss' => [
        '325106',
        '317437',
        '280715',
        // '332152', 未稼働
    ],
    'search_cate' => [
        '051100000',
        '051110000',
        '051111000',
        '052491000',
        '052500000',
        '052810000',
        '052820000',
        '052913000',
        '052920000',
        '052930000',
        '052940000',
        '052955000',
        '053300000',
        '053310000',
        '053395000',
        '053400000',
        '054110000',
        '054111000',
        '055100000',
        '055193000',
        '055200000',
        '055300000',
        '055392000',
        '055400000',
        '055450000',
        '055500000',
        '055600000',
        '055901000',
        '055930000',
        '056110000',
        '056190000',
        '056410000',
        '058998000',
    ],
    'items' => [
        'TY' => [
            "NANOENERGY 0",
            "NANOENERGY 2",
            "NANOENERGY 3",
            "NANOENERGY 3 plus",
            "NANOENERGY M136",
            "NANOENERGY M134E",
            "PROXES CF2",
            "PROXES CF2 SUV",
            "PROXES T1 Sport",
            "PROXES T1 Sport SUV",
            "PROXES C1S",
            "PROXES C1S spec-a",
            "PROXES T1R",
            "PROXES R1R",
            "PROXES R888",
            "PROXES S/T",
            "TRANPATH SU sport",
            "TRANPATH S/U",
            "TRANPATH A/T",
            "TRANPATH Lu",
            "TRANPATH LuⅡ",
            "TRANPATH LuK",
            "TRANPATH　MPZ",
            "TRANPATH M/T",
            "TRANPATH ML",
            "TEO plus",
            "ECO WALKER",
            "DRB",
            "V-02",
            "V-02e",
            "H20",
            "i A06",
            "i J18",
            "J55",
            "J60",
            "LIZA CLT",
            "DELVEX M134",
            "DELVEX M634",
            "M136 ZEROSYS",
            "M131",
            "M133",
            "M319",
            "M637",
            "M501",
            "M614",
            "GARIT GIZ",
            "GARIT G5",
            "TRANPATH MK4α",
            "OBSERVE GSi-5",
            "DELVEX 934",
            "DELVEX M934",
            "DELVEX M917",
            "GARIT G30",
            "OBSERVE GARIT SV For Taxi",
        ],
        'DF' => [
            "ZIEX ZE912",
            "ZIEX ZE914",
            "SINCERA SN828",
            "エナセーブ EC202",
            "エナセーブ EC203",
            "エナセーブ PREMIUM",
            "エナセーブ RV503★",
            "エナセーブ VAN01",
            "エナセーブ SPLT38",
            "エナセーブ NEXT",
            "エナセーブ 100",
            "LE MANS4",
            "VEURO VE303",
            "MAXX GT",
            "MAXX TT",
            "QUATTROMAXX",
            "DIREZZA ZⅡ",
            "DIREZZA DZ102",
            "GRANDTREK",
            "GRANDTREK PT3",
            "GRANDTREK AT3",
            "GRANDTREK MT2",
            "GRANDTREK TG4",
            "DV-01",
            "SPLT5",
            "SPLT21",
            "SPLT33",
            "SP185",
            "SP229",
            "SP355",
            "SP485",
            "SP495",
            "SP655",
            "SP770",
            "VAN CUSTOM",
            "RV503",
            "LINAM G2",
            "LINAM M2",
            "WINTER MAXX WM01",
            "WINTER MAXX WM02",
            "WINTER MAXX SJ8",
            "WINTER MAXX SV01",
            "DSX-2",
        ],
        'BS' => [
            "FR-10",
            "SNEAKER",
            "NEXTRY",
            "ECOPIA EP001S",
            "ECOPIA EV-01",
            "ECOPIA PZ-X",
            "ECOPIA PZ-XC",
            "ECOPIA PRV",
            "ECOPIA EX20",
            "ECOPIA EX20RV",
            "ECOPIA EX20C",
            "ECOPIA EX20C TYPE-H",
            "Playz PZ-X",
            "Playz PZ-XC",
            "Playz PX-C",
            "REGNO GR-XI",
            "REGNO GR-XT",
            "REGNO GR-9000",
            "REGNO GRVⅡ",
            "REGNO GRV",
            "REGNO GR-LEGGERA",
            "POTENZA RE-71R",
            "POTENZA RE-11",
            "POTENZA S001",
            "POTENZA RE003",
            "DUELER H/L850",
            "DUELER H/P SPORT",
            "DUELER H/P680",
            "DUELER A/T694",
            "DUELER M/T674",
            "DUELER H/L683",
            "ECOPIAR 680",
            "V600",
            "DURAVIS R670",
            "DURAVIS 604V",
            "DURAVIS 605V",
            "DURAVIS 610V",
            "DURAVIS 650V",
            "DURAVIS G561",
            "DURAVIS R205",
            "DURAVIS M804",
            "DURAVIS M810",
            "ECOPIA R201",
            "ECOPIA M812",
            "BLIZZAK VRX",
            "BLIZZAK REVO GZ",
            "BLIZZAK REVO2",
            "BLIZZAK REVO1",
            "BLIZZAK DM-V2",
            "BLIZZAK DM-V1",
            "BLIZZAK DM-Z3",
            "BLIZZAK REVO969",
            "BLIZZAK W969",
            "BLIZZAK W300",
            "BLIZZAK W965",
        ],
        'YH' => [
            "ECOS ES31",
            "BluEarth-1 EF20",
            "BluEarth-A",
            "BluEarth AE-01F",
            "BluEarth RV-02",
            "ADVAN V105",
            "ADVAN Sport",
            "ADVAN dB",
            "ADVAN NEOVA",
            "ADVAN FLEVA",
            "ADVAN S.T.",
            "S.drive",
            "PARADA Spec-X",
            "GEOLANDAR SUV",
            "GEOLANDAR M/T+",
            "GEOLANDAR A/T-S",
            "GEOLANDAR H/T-S",
            "BluEarth LT152R",
            "LT151R",
            "JOB RY52",
            "LY018",
            "MY807",
            "RY01",
            "RY206",
            "RY208",
            "TY285",
            "Y20",
            "Y45",
            "Y227",
            "Y356",
            "Y757",
            "Y761",
            "Y765L",
            "Y776",
            "Y823",
            "Y825",
            "Y828",
            "ice GUARD IG30PL",
            "ice GUARD IG50PL",
            "ice GUARD G075",
            "ice GUARD IG91",
            "GEOLANDAR IT-SG072",
            "GEOLANDAR IT-SG073",
        ],
    ],
    'car_regions' => [
        '北海道・東北' => [
            '北海道' => [
                "函館",
                "北見",
                "室蘭",
                "帯広",
                "旭川",
                "札幌",
                "釧路",
            ],
            '青森県' => [
                "八戸",
                "青森",
            ],
            '岩手県' => [
                "岩手",
                "平泉",
                "盛岡",
            ],
            '宮城県' => [
                "仙台",
                "宮城",
            ],
            '秋田県' => [
                "秋田",
            ],
            '山形県' => [
                "山形",
                "庄内",
            ],
            '福島県' => [
                "いわき",
                "会津",
                "福島",
                "郡山",
            ],
        ],
        '関東' => [
            '茨城県' => [
                "つくば",
                "土浦",
                "水戸",
            ],
            '栃木県' => [
                "とちぎ",
                "宇都宮",
                "那須",
            ],
            '群馬県' => [
                "前橋",
                "群馬",
                "高崎",
            ],
            '埼玉県' => [
                "大宮",
                "川口",
                "川越",
                "所沢",
                "春日部",
                "熊谷",
                "越谷",
            ],
            '千葉県' => [
                "千葉",
                "成田",
                "柏",
                "習志野",
                "袖ヶ浦",
                "野田",
            ],
            '東京都' => [
                "世田谷",
                "八王子",
                "品川",
                "多摩",
                "杉並",
                "練馬",
                "足立",
            ],
            '神奈川県' => [
                "川崎",
                "横浜",
                "湘南",
                "相模",
            ],
        ],
        '中部' => [
            '新潟県' => [
                "新潟",
                "長岡",
            ],
            '富山県' => [
                "富山",
            ],
            '石川県' => [
                "石川",
                "金沢",
            ],
            '福井県' => [
                "福井",
            ],
            '山梨県' => [
                "富士山",
                "山梨",
            ],
            '長野県' => [
                "松本",
                "諏訪",
                "長野",
            ],
            '岐阜県' => [
                "岐阜",
                "飛騨",
            ],
            '静岡県' => [
                "伊豆",
                "富士山",
                "沼津",
                "浜松",
                "静岡",
            ],
            '愛知県' => [
                "一宮",
                "三河",
                "名古屋",
                "尾張小牧",
                "岡崎",
                "春日井",
                "豊橋",
                "豊田",
            ],
        ],
        '近畿' => [
            '三重県' => [
                "三重",
                "鈴鹿",
            ],
            '滋賀県' => [
                "滋賀",
            ],
            '京都府' => [
                "京都",
            ],
            '大阪府' => [
                "なにわ",
                "和泉",
                "堺",
                "大阪",
            ],
            '兵庫県' => [
                "姫路",
                "神戸",
            ],
            '奈良県' => [
                "奈良",
            ],
            '和歌山県' => [
                "和歌山",
            ],
        ],
        '中国・四国' => [
            '鳥取県' => [
                "鳥取",
            ],
            '島根県' => [
                "島根",
            ],
            '岡山県' => [
                "倉敷",
                "岡山",
            ],
            '広島県' => [
                "広島",
                "福山",
            ],
            '山口県' => [
                "下関",
                "山口",
            ],
            '徳島県' => [
                "徳島",
            ],
            '香川県' => [
                "香川",
            ],
            '愛媛県' => [
                "愛媛",
            ],
            '高知県' => [
                "高知",
            ],
        ],
        '九州・沖縄' => [
            '福岡県' => [
                "久留米",
                "北九州",
                "福岡",
                "筑豊",
            ],
            '佐賀県' => [
                "佐賀",
            ],
            '長崎県' => [
                "佐世保",
                "長崎",
            ],
            '熊本県' => [
                "熊本",
            ],
            '大分県' => [
                "大分",
            ],
            '宮崎県' => [
                "宮崎",
            ],
            '鹿児島県' => [
                "奄美",
                "鹿児島",
            ],
            '沖縄県' => [
                "沖縄",
            ],
        ]
    ],
    'car_size' => [
        '0' => '',
        '1' => '軽自動車（乗用・貨物）',
        '2' => '普通乗用車 5・7ナンバー',
        '3' => '普通乗用車 3ナンバー',
        '4' => '小型貨物 4ナンバー',
        '5' => '普通貨物 1ナンバー',
    ],
    'car_weight_1' => [
        '0' => '',
        '1' => '軽自動車',
    ],
    'car_weight_2' => [
        '0' => '',
        '1' => '1000kg',
        '2' => '1500kg',
        '3' => '2000kg',
        '4' => '2500kg',
        '5' => '3000kg',
    ],
    'car_weight_3' => [
        '0' => '',
        '1' => '1000kg',
        '2' => '1500kg',
        '3' => '2000kg',
        '4' => '2500kg',
        '5' => '3000kg',
    ],
    'car_weight_4' => [
        '0' => '',
        '1' => '車両重量～2000kg',
        '2' => '車両重量～2500kg',
        '3' => '車両重量～3000kg',
        '4' => '車両重量～4000kg',
    ],
    'car_weight_5' => [
        '0' => '',
        '1' => '車両重量～2000kg',
        '2' => '車両重量～2500kg',
        '3' => '車両重量～3000kg',
        '4' => '車両重量～4000kg',
    ],
    'TYPE_MEMBER' => 1,
    'TYPE_CARD' => 2,
    'TYPE_GUEST' => 3,
    'DEFAULT_NUMBER_PRODUCT' => 10,
    'DEFAULT_NUMBER_CAR' => 5
];
