<?php
/**
 * Created by PhpStorm.
 * User: Huy
 * Date: 8/15/2016
 * Time: 10:02 AM
 */

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\db\Query;

class FeeBasic extends ActiveRecord
{
    public static function tableName()
    {
        return 'FEE_BASIC';
    }

    public function getWhere($filters = [], $select = '*')
    {
        $query = new Query();
        $query->select($select)->from(static::tableName());

        $login_info = Yii::$app->session->get('login_info');
        if (isset($login_info['M50_SS_CD']) && $login_info['M50_SS_CD'] != '') {
            $query->andWhere('SS_CD =:ss_cd', [':ss_cd' => $login_info['M50_SS_CD']]);
        }
        if (isset($filters['ID']) && $filters['ID']) {
            $query->andwhere('ID = ' . $filters['ID']);
        }
       
        if (isset($filters['offset']) && $filters['offset']) {
            $query->offset($filters['offset']);
        }

        if (isset($filters['limit']) && $filters['limit']) {
            $query->limit($filters['limit']);
        }

        return $query;
    }

    public function getData($filters = [], $select = '*')
    {
        $query = $this->getWhere($filters, $select);
        $query->orderBy('ID DESC');
        return $query->all();
    }

    public function countData($filters = [], $select = 'ID')
    {
        $query = $this->getWhere($filters);
        return $query->count();
    }

    public function getSeq()
    {
        $command = \Yii::$app->db->createCommand('SELECT FEE_BASIC_SEQ.nextval FROM dual');
        $res = $command->queryAll();
        return $res['0']['NEXTVAL'];
    }

    public function beforeSave($insert)
    {
        $this->UPDATED_AT = new Expression("CURRENT_DATE");
        if (!$this->ID) {
            $this->CREATED_AT = new Expression("CURRENT_DATE");
            $this->ID = $this->getSeq();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}